import { type ClassValue, clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

// Teach tailwind-merge the named tokens from styles/tokens.css so that, for
// example, `h-control-sm` correctly overrides `h-control-md`.
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      spacing: [
        "control-xs",
        "control-sm",
        "control-md",
        "control-lg",
        "button-xs",
        "button-sm",
        "button-md",
        "button-lg",
        "icon-button-xs",
        "icon-button-sm",
        "icon-button-md",
        "icon-button-lg",
        "icon-xs",
        "icon-sm",
        "icon-md",
        "icon-lg",
        "pill",
        "pill-x",
        "row",
        "row-sm",
        "kbd",
        "menu",
        "composer",
        "sidebar",
        "sidebar-min",
        "sidebar-max",
        "sidebar-strip",
        "nav-row",
        "nav-header",
        "nav-search",
        "resize-handle",
        "surface-inset",
        "switch-width",
        "switch-height",
        "switch-thumb",
        "switch-travel",
        "settings-control",
        "page-toolbar",
        "titlebar",
        "titlebar-nav-end",
        "titlebar-start",
        "traffic-lights",
        "setup",
        "setup-card",
        "summary-inset",
      ],
      container: ["thread", "setup", "summary", "summary-stack", "settings", "settings-wide"],
      radius: [
        "document",
        "control",
        "surface",
        "dialog",
        "thread",
        "composer",
        "rail",
        "menu",
        "tooltip",
        "capsule",
        "page",
        "nav",
        "settings",
        "summary",
      ],
      shadow: ["hairline", "menu", "tooltip", "summary", "thumb", "page"],
      text: ["code", "code-inline", "page-title", "label", "nav-title"],
      tracking: ["hero", "section", "eyebrow"],
      font: ["display"],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
